---
- hosts: azure
  sudo: yes
  tasks:
    - name: Instalar
      apt: name={{item}} state=present
      with_items:
        - python-pip
        - python-virtualenv
        - python-psycopg2
        - postgresql
        - libpq-dev
        - gunicorn

    - name: cambiar puertos
      command: iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 5000

- hosts: azure
  tasks:
    - name: Clonar repo
      git:
        repo: https://github.com/jabonillab/ProyectoCC2018.git
        dest: ~/ProyectoCC2018
        force: yes
    - name: Entorno
      pip:
        requirements: ~/ProyectoCC2018/requirements.txt
        virtualenv: ~/ProyectoCC2018/venv

- hosts: azure
  become: yes
  become_user: postgres
  gather_facts: no

  vars:
    dbname: jorgedb
    dbuser: postgres
    dbpassword: 123456789

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}
