language: python
python:
- '3.6'
install: pip install -e .
script: python tests/test_productos.py  
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE jorgedb;" -U postgres
  - psql -c "CREATE USER jorge4138 WITH PASSWORD '1234';" -U postgres